### PR TITLE
Add Events to fix command issues

### LINKED ISSUE #168: Scroll doesn't reset to top if list is performed after filtering
1. list s/read by/title
2. list -> Scrolled to bottom

### PR DESCRIPTION
**Pull request by qiu-siqi**
- Fix selection issues for edit and delete
- Fix scroll issue for list (Fixes #168)

### CODE REVIEW

File: src/main/java/seedu/address/ui/BookListPanel.java [hunk 1]
```diff
@@ -70,6 +82,22 @@ private void scrollTo(int index) {
         bookListView.getSelectionModel().clearAndSelect(index);
     }
 
+    /**
+     * Reselects the book that was previously deselected by {@code deselectBook()}, if any.
+     * The book also needs to be in the display book list.
+     * @return whether the previous book selection is reselected.
+     */
+    protected boolean reselectBook() {
```
Comment (takuyakanbr) [inline src/main/java/seedu/address/ui/BookListPanel.java]: Refactor this method. Move the assignment outside the `if` condition.
